version: "3"
silent: true

tasks:
  watch: dotnet watch --project ./Ogma3.AppHost/Ogma3.AppHost.csproj

  watch-dbg:
    env:
      Microsoft_CodeAnalysis_EditAndContinue_LogDir: '{{.TASKFILE_DIR | toSlash}}/.logs/{{now | date "2006-01-02_15-04-05"}}'
    cmds:
      - echo "Logging to $Microsoft_CodeAnalysis_EditAndContinue_LogDir"
      - dotnet watch --verbose --project ./Ogma3.AppHost/Ogma3.AppHost.csproj

  run-prod: dotnet run -c release --project ./Ogma3.AppHost/Ogma3.AppHost.csproj -- --emulate-prod

  # Generate JS API clients based on Swagger
  paths:
    env:
      DENO_TLS_CA_STORE: system
    vars:
      DEST: ./Ogma3/FrontendCode/typescript/generated/
      URL: https://localhost:5001/openapi/
    cmds:
      - ogma-tool generate-paths {{.DEST}} --path.public="{{.URL}}public.json" --path.internal="{{.URL}}internal.json"

  # Generate preload code for fonts
  preloads:
    vars:
      SRC: ./Ogma3/wwwroot/fonts
      DEST: fonts
    cmds:
      - ogma-tool generate-preloads {{.SRC}} {{.DEST}}

  # Generate CSS import conde for fonts
  imports:
    vars:
      SRC: ./Ogma3/wwwroot/fonts
      DEST: fonts
    cmds:
      - ogma-tool generate-imports {{.SRC}} {{.DEST}}

  # Download a new icon
  get-icon:
    dir: ./Ogma3/FrontendCode
    cmds:
      - bun ./scripts/icon-dl.ts

  # Check the size of the bundle
  bundlesize:
    vars:
      SRC: ./Ogma3/wwwroot/js/*.js ./Ogma3/wwwroot/js/**/*.js
    cmds:
      - ogma-tool bundle-size {{.SRC}}

  # Get Lighthouse CLI score
  score:
    cmds:
      - dotnet run -c release --project ./Ogma3/Ogma3.csproj --environment testing
      - lighthouse https://localhost:5001 --view

  # EF helpers
  db-migrate: dotnet ef migrations add --project ./Ogma3/Ogma3.csproj {{.CLI_ARGS}}
  db-up: dotnet ef database update --project ./Ogma3/Ogma3.csproj {{.CLI_ARGS}}
  db-compile: dotnet ef dbcontext optimize --project ./Ogma3/Ogma3.csproj --output-dir CompiledModels --namespace CompiledModels {{.CLI_ARGS}}
  db-all:
    cmds:
      - task: db-migrate
      - task: db-up
      - task: db-compile
