/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddBookToShelfResult
 */
export interface AddBookToShelfResult {
    /**
     * 
     * @type {number}
     * @memberof AddBookToShelfResult
     */
    shelfId?: number;
    /**
     * 
     * @type {number}
     * @memberof AddBookToShelfResult
     */
    storyId?: number;
}

export function AddBookToShelfResultFromJSON(json: any): AddBookToShelfResult {
    return AddBookToShelfResultFromJSONTyped(json, false);
}

export function AddBookToShelfResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddBookToShelfResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shelfId': !exists(json, 'shelfId') ? undefined : json['shelfId'],
        'storyId': !exists(json, 'storyId') ? undefined : json['storyId'],
    };
}

export function AddBookToShelfResultToJSON(value?: AddBookToShelfResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shelfId': value.shelfId,
        'storyId': value.storyId,
    };
}

