/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OgmaUser,
    OgmaUserFromJSON,
    OgmaUserFromJSONTyped,
    OgmaUserToJSON,
} from './OgmaUser';
import {
    Tag,
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';

/**
 * 
 * @export
 * @interface BlacklistedTag
 */
export interface BlacklistedTag {
    /**
     * 
     * @type {OgmaUser}
     * @memberof BlacklistedTag
     */
    user?: OgmaUser | null;
    /**
     * 
     * @type {number}
     * @memberof BlacklistedTag
     */
    userId?: number;
    /**
     * 
     * @type {Tag}
     * @memberof BlacklistedTag
     */
    tag?: Tag | null;
    /**
     * 
     * @type {number}
     * @memberof BlacklistedTag
     */
    tagId?: number;
}

export function BlacklistedTagFromJSON(json: any): BlacklistedTag {
    return BlacklistedTagFromJSONTyped(json, false);
}

export function BlacklistedTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlacklistedTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : OgmaUserFromJSON(json['user']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'tag': !exists(json, 'tag') ? undefined : TagFromJSON(json['tag']),
        'tagId': !exists(json, 'tagId') ? undefined : json['tagId'],
    };
}

export function BlacklistedTagToJSON(value?: BlacklistedTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': OgmaUserToJSON(value.user),
        'userId': value.userId,
        'tag': TagToJSON(value.tag),
        'tagId': value.tagId,
    };
}

