/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockUserCommand
 */
export interface BlockUserCommand {
    /**
     * 
     * @type {string}
     * @memberof BlockUserCommand
     */
    name?: string | null;
}

export function BlockUserCommandFromJSON(json: any): BlockUserCommand {
    return BlockUserCommandFromJSONTyped(json, false);
}

export function BlockUserCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockUserCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function BlockUserCommandToJSON(value?: BlockUserCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

