/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Comment,
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
} from './Comment';

/**
 * 
 * @export
 * @interface CommentRevisionAllOf
 */
export interface CommentRevisionAllOf {
    /**
     * 
     * @type {Date}
     * @memberof CommentRevisionAllOf
     */
    editTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof CommentRevisionAllOf
     */
    body?: string | null;
    /**
     * 
     * @type {Comment}
     * @memberof CommentRevisionAllOf
     */
    parent?: Comment | null;
    /**
     * 
     * @type {number}
     * @memberof CommentRevisionAllOf
     */
    parentId?: number;
}

export function CommentRevisionAllOfFromJSON(json: any): CommentRevisionAllOf {
    return CommentRevisionAllOfFromJSONTyped(json, false);
}

export function CommentRevisionAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentRevisionAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'editTime': !exists(json, 'editTime') ? undefined : (new Date(json['editTime'])),
        'body': !exists(json, 'body') ? undefined : json['body'],
        'parent': !exists(json, 'parent') ? undefined : CommentFromJSON(json['parent']),
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
    };
}

export function CommentRevisionAllOfToJSON(value?: CommentRevisionAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'editTime': value.editTime === undefined ? undefined : (value.editTime.toISOString()),
        'body': value.body,
        'parent': CommentToJSON(value.parent),
        'parentId': value.parentId,
    };
}

