/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseModel,
    BaseModelFromJSON,
    BaseModelFromJSONTyped,
    BaseModelToJSON,
} from './BaseModel';
import {
    Comment,
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
} from './Comment';
import {
    CommentRevisionAllOf,
    CommentRevisionAllOfFromJSON,
    CommentRevisionAllOfFromJSONTyped,
    CommentRevisionAllOfToJSON,
} from './CommentRevisionAllOf';

/**
 * 
 * @export
 * @interface CommentRevision
 */
export interface CommentRevision {
    /**
     * 
     * @type {number}
     * @memberof CommentRevision
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CommentRevision
     */
    editTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof CommentRevision
     */
    body?: string | null;
    /**
     * 
     * @type {Comment}
     * @memberof CommentRevision
     */
    parent?: Comment | null;
    /**
     * 
     * @type {number}
     * @memberof CommentRevision
     */
    parentId?: number;
}

export function CommentRevisionFromJSON(json: any): CommentRevision {
    return CommentRevisionFromJSONTyped(json, false);
}

export function CommentRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentRevision {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'editTime': !exists(json, 'editTime') ? undefined : (new Date(json['editTime'])),
        'body': !exists(json, 'body') ? undefined : json['body'],
        'parent': !exists(json, 'parent') ? undefined : CommentFromJSON(json['parent']),
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
    };
}

export function CommentRevisionToJSON(value?: CommentRevision | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'editTime': value.editTime === undefined ? undefined : (value.editTime.toISOString()),
        'body': value.body,
        'parent': CommentToJSON(value.parent),
        'parentId': value.parentId,
    };
}

