/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseModel,
    BaseModelFromJSON,
    BaseModelFromJSONTyped,
    BaseModelToJSON,
} from './BaseModel';
import {
    ContentBlockAllOf,
    ContentBlockAllOfFromJSON,
    ContentBlockAllOfFromJSONTyped,
    ContentBlockAllOfToJSON,
} from './ContentBlockAllOf';
import {
    OgmaUser,
    OgmaUserFromJSON,
    OgmaUserFromJSONTyped,
    OgmaUserToJSON,
} from './OgmaUser';

/**
 * 
 * @export
 * @interface ContentBlock
 */
export interface ContentBlock {
    /**
     * 
     * @type {number}
     * @memberof ContentBlock
     */
    id: number;
    /**
     * 
     * @type {OgmaUser}
     * @memberof ContentBlock
     */
    issuer?: OgmaUser | null;
    /**
     * 
     * @type {number}
     * @memberof ContentBlock
     */
    issuerId?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentBlock
     */
    reason?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ContentBlock
     */
    dateTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ContentBlock
     */
    type?: string | null;
}

export function ContentBlockFromJSON(json: any): ContentBlock {
    return ContentBlockFromJSONTyped(json, false);
}

export function ContentBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'issuer': !exists(json, 'issuer') ? undefined : OgmaUserFromJSON(json['issuer']),
        'issuerId': !exists(json, 'issuerId') ? undefined : json['issuerId'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'dateTime': !exists(json, 'dateTime') ? undefined : (new Date(json['dateTime'])),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ContentBlockToJSON(value?: ContentBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'issuer': OgmaUserToJSON(value.issuer),
        'issuerId': value.issuerId,
        'reason': value.reason,
        'dateTime': value.dateTime === undefined ? undefined : (value.dateTime.toISOString()),
        'type': value.type,
    };
}

