/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFaqCommand
 */
export interface CreateFaqCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateFaqCommand
     */
    question?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateFaqCommand
     */
    answer?: string | null;
}

export function CreateFaqCommandFromJSON(json: any): CreateFaqCommand {
    return CreateFaqCommandFromJSONTyped(json, false);
}

export function CreateFaqCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFaqCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'question': !exists(json, 'question') ? undefined : json['question'],
        'answer': !exists(json, 'answer') ? undefined : json['answer'],
    };
}

export function CreateFaqCommandToJSON(value?: CreateFaqCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'question': value.question,
        'answer': value.answer,
    };
}

