/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EClubMemberRoles {
    Founder = 'Founder',
    Admin = 'Admin',
    Moderator = 'Moderator',
    User = 'User'
}

export function EClubMemberRolesFromJSON(json: any): EClubMemberRoles {
    return EClubMemberRolesFromJSONTyped(json, false);
}

export function EClubMemberRolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EClubMemberRoles {
    return json as EClubMemberRoles;
}

export function EClubMemberRolesToJSON(value?: EClubMemberRoles | null): any {
    return value as any;
}

