/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ENotificationEvent,
    ENotificationEventFromJSON,
    ENotificationEventFromJSONTyped,
    ENotificationEventToJSON,
} from './ENotificationEvent';

/**
 * 
 * @export
 * @interface GetUserNotificationsResult
 */
export interface GetUserNotificationsResult {
    /**
     * 
     * @type {number}
     * @memberof GetUserNotificationsResult
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserNotificationsResult
     */
    body?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserNotificationsResult
     */
    url?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetUserNotificationsResult
     */
    dateTime?: Date;
    /**
     * 
     * @type {ENotificationEvent}
     * @memberof GetUserNotificationsResult
     */
    event?: ENotificationEvent;
    /**
     * 
     * @type {string}
     * @memberof GetUserNotificationsResult
     */
    message?: string | null;
}

export function GetUserNotificationsResultFromJSON(json: any): GetUserNotificationsResult {
    return GetUserNotificationsResultFromJSONTyped(json, false);
}

export function GetUserNotificationsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserNotificationsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'dateTime': !exists(json, 'dateTime') ? undefined : (new Date(json['dateTime'])),
        'event': !exists(json, 'event') ? undefined : ENotificationEventFromJSON(json['event']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function GetUserNotificationsResultToJSON(value?: GetUserNotificationsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'body': value.body,
        'url': value.url,
        'dateTime': value.dateTime === undefined ? undefined : (value.dateTime.toISOString()),
        'event': ENotificationEventToJSON(value.event),
        'message': value.message,
    };
}

