/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityUserOfLong
 */
export interface IdentityUserOfLong {
    /**
     * 
     * @type {number}
     * @memberof IdentityUserOfLong
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    normalizedUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    normalizedEmail?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUserOfLong
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    passwordHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    securityStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    concurrencyStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserOfLong
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUserOfLong
     */
    phoneNumberConfirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUserOfLong
     */
    twoFactorEnabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof IdentityUserOfLong
     */
    lockoutEnd?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUserOfLong
     */
    lockoutEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IdentityUserOfLong
     */
    accessFailedCount?: number;
}

export function IdentityUserOfLongFromJSON(json: any): IdentityUserOfLong {
    return IdentityUserOfLongFromJSONTyped(json, false);
}

export function IdentityUserOfLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityUserOfLong {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'normalizedUserName': !exists(json, 'normalizedUserName') ? undefined : json['normalizedUserName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'normalizedEmail': !exists(json, 'normalizedEmail') ? undefined : json['normalizedEmail'],
        'emailConfirmed': !exists(json, 'emailConfirmed') ? undefined : json['emailConfirmed'],
        'passwordHash': !exists(json, 'passwordHash') ? undefined : json['passwordHash'],
        'securityStamp': !exists(json, 'securityStamp') ? undefined : json['securityStamp'],
        'concurrencyStamp': !exists(json, 'concurrencyStamp') ? undefined : json['concurrencyStamp'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'phoneNumberConfirmed': !exists(json, 'phoneNumberConfirmed') ? undefined : json['phoneNumberConfirmed'],
        'twoFactorEnabled': !exists(json, 'twoFactorEnabled') ? undefined : json['twoFactorEnabled'],
        'lockoutEnd': !exists(json, 'lockoutEnd') ? undefined : (json['lockoutEnd'] === null ? null : new Date(json['lockoutEnd'])),
        'lockoutEnabled': !exists(json, 'lockoutEnabled') ? undefined : json['lockoutEnabled'],
        'accessFailedCount': !exists(json, 'accessFailedCount') ? undefined : json['accessFailedCount'],
    };
}

export function IdentityUserOfLongToJSON(value?: IdentityUserOfLong | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userName': value.userName,
        'normalizedUserName': value.normalizedUserName,
        'email': value.email,
        'normalizedEmail': value.normalizedEmail,
        'emailConfirmed': value.emailConfirmed,
        'passwordHash': value.passwordHash,
        'securityStamp': value.securityStamp,
        'concurrencyStamp': value.concurrencyStamp,
        'phoneNumber': value.phoneNumber,
        'phoneNumberConfirmed': value.phoneNumberConfirmed,
        'twoFactorEnabled': value.twoFactorEnabled,
        'lockoutEnd': value.lockoutEnd === undefined ? undefined : (value.lockoutEnd === null ? null : value.lockoutEnd.toISOString()),
        'lockoutEnabled': value.lockoutEnabled,
        'accessFailedCount': value.accessFailedCount,
    };
}

