/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InfractionType,
    InfractionTypeFromJSON,
    InfractionTypeFromJSONTyped,
    InfractionTypeToJSON,
} from './InfractionType';
import {
    OgmaUser,
    OgmaUserFromJSON,
    OgmaUserFromJSONTyped,
    OgmaUserToJSON,
} from './OgmaUser';

/**
 * 
 * @export
 * @interface InfractionAllOf
 */
export interface InfractionAllOf {
    /**
     * 
     * @type {OgmaUser}
     * @memberof InfractionAllOf
     */
    user?: OgmaUser;
    /**
     * 
     * @type {number}
     * @memberof InfractionAllOf
     */
    userId?: number;
    /**
     * 
     * @type {Date}
     * @memberof InfractionAllOf
     */
    issueDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InfractionAllOf
     */
    activeUntil?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InfractionAllOf
     */
    removedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InfractionAllOf
     */
    reason?: string;
    /**
     * 
     * @type {InfractionType}
     * @memberof InfractionAllOf
     */
    type?: InfractionType;
    /**
     * 
     * @type {OgmaUser}
     * @memberof InfractionAllOf
     */
    issuedBy?: OgmaUser;
    /**
     * 
     * @type {number}
     * @memberof InfractionAllOf
     */
    issuedById?: number;
    /**
     * 
     * @type {OgmaUser}
     * @memberof InfractionAllOf
     */
    removedBy?: OgmaUser | null;
    /**
     * 
     * @type {number}
     * @memberof InfractionAllOf
     */
    removedById?: number | null;
}

export function InfractionAllOfFromJSON(json: any): InfractionAllOf {
    return InfractionAllOfFromJSONTyped(json, false);
}

export function InfractionAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfractionAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : OgmaUserFromJSON(json['user']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'issueDate': !exists(json, 'issueDate') ? undefined : (new Date(json['issueDate'])),
        'activeUntil': !exists(json, 'activeUntil') ? undefined : (new Date(json['activeUntil'])),
        'removedAt': !exists(json, 'removedAt') ? undefined : (json['removedAt'] === null ? null : new Date(json['removedAt'])),
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'type': !exists(json, 'type') ? undefined : InfractionTypeFromJSON(json['type']),
        'issuedBy': !exists(json, 'issuedBy') ? undefined : OgmaUserFromJSON(json['issuedBy']),
        'issuedById': !exists(json, 'issuedById') ? undefined : json['issuedById'],
        'removedBy': !exists(json, 'removedBy') ? undefined : OgmaUserFromJSON(json['removedBy']),
        'removedById': !exists(json, 'removedById') ? undefined : json['removedById'],
    };
}

export function InfractionAllOfToJSON(value?: InfractionAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': OgmaUserToJSON(value.user),
        'userId': value.userId,
        'issueDate': value.issueDate === undefined ? undefined : (value.issueDate.toISOString()),
        'activeUntil': value.activeUntil === undefined ? undefined : (value.activeUntil.toISOString()),
        'removedAt': value.removedAt === undefined ? undefined : (value.removedAt === null ? null : value.removedAt.toISOString()),
        'reason': value.reason,
        'type': InfractionTypeToJSON(value.type),
        'issuedBy': OgmaUserToJSON(value.issuedBy),
        'issuedById': value.issuedById,
        'removedBy': OgmaUserToJSON(value.removedBy),
        'removedById': value.removedById,
    };
}

