/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinClubCommand
 */
export interface JoinClubCommand {
    /**
     * 
     * @type {number}
     * @memberof JoinClubCommand
     */
    clubId?: number;
}

export function JoinClubCommandFromJSON(json: any): JoinClubCommand {
    return JoinClubCommandFromJSONTyped(json, false);
}

export function JoinClubCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinClubCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clubId': !exists(json, 'clubId') ? undefined : json['clubId'],
    };
}

export function JoinClubCommandToJSON(value?: JoinClubCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clubId': value.clubId,
    };
}

