/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlacklistedRating,
    BlacklistedRatingFromJSON,
    BlacklistedRatingFromJSONTyped,
    BlacklistedRatingToJSON,
} from './BlacklistedRating';
import {
    BlacklistedTag,
    BlacklistedTagFromJSON,
    BlacklistedTagFromJSONTyped,
    BlacklistedTagToJSON,
} from './BlacklistedTag';
import {
    Blogpost,
    BlogpostFromJSON,
    BlogpostFromJSONTyped,
    BlogpostToJSON,
} from './Blogpost';
import {
    Club,
    ClubFromJSON,
    ClubFromJSONTyped,
    ClubToJSON,
} from './Club';
import {
    CommentsThread,
    CommentsThreadFromJSON,
    CommentsThreadFromJSONTyped,
    CommentsThreadToJSON,
} from './CommentsThread';
import {
    Infraction,
    InfractionFromJSON,
    InfractionFromJSONTyped,
    InfractionToJSON,
} from './Infraction';
import {
    Notification,
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
} from './Notification';
import {
    OgmaRole,
    OgmaRoleFromJSON,
    OgmaRoleFromJSONTyped,
    OgmaRoleToJSON,
} from './OgmaRole';
import {
    OgmaUser,
    OgmaUserFromJSON,
    OgmaUserFromJSONTyped,
    OgmaUserToJSON,
} from './OgmaUser';
import {
    Report,
    ReportFromJSON,
    ReportFromJSONTyped,
    ReportToJSON,
} from './Report';
import {
    Story,
    StoryFromJSON,
    StoryFromJSONTyped,
    StoryToJSON,
} from './Story';
import {
    UserRole,
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
} from './UserRole';

/**
 * 
 * @export
 * @interface OgmaUserAllOf
 */
export interface OgmaUserAllOf {
    /**
     * 
     * @type {string}
     * @memberof OgmaUserAllOf
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OgmaUserAllOf
     */
    bio?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OgmaUserAllOf
     */
    links?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OgmaUserAllOf
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof OgmaUserAllOf
     */
    avatarId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OgmaUserAllOf
     */
    registrationDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OgmaUserAllOf
     */
    lastActive?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OgmaUserAllOf
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {CommentsThread}
     * @memberof OgmaUserAllOf
     */
    commentsThread?: CommentsThread;
    /**
     * 
     * @type {Array<UserRole>}
     * @memberof OgmaUserAllOf
     */
    userRoles?: Array<UserRole> | null;
    /**
     * 
     * @type {Array<Story>}
     * @memberof OgmaUserAllOf
     */
    stories?: Array<Story>;
    /**
     * 
     * @type {Array<Blogpost>}
     * @memberof OgmaUserAllOf
     */
    blogposts?: Array<Blogpost>;
    /**
     * 
     * @type {Array<OgmaRole>}
     * @memberof OgmaUserAllOf
     */
    roles?: Array<OgmaRole>;
    /**
     * 
     * @type {Array<BlacklistedRating>}
     * @memberof OgmaUserAllOf
     */
    blacklistedRatings?: Array<BlacklistedRating>;
    /**
     * 
     * @type {Array<BlacklistedTag>}
     * @memberof OgmaUserAllOf
     */
    blacklistedTags?: Array<BlacklistedTag>;
    /**
     * 
     * @type {Array<OgmaUser>}
     * @memberof OgmaUserAllOf
     */
    blockers?: Array<OgmaUser>;
    /**
     * 
     * @type {Array<OgmaUser>}
     * @memberof OgmaUserAllOf
     */
    blocking?: Array<OgmaUser>;
    /**
     * 
     * @type {Array<OgmaUser>}
     * @memberof OgmaUserAllOf
     */
    followers?: Array<OgmaUser>;
    /**
     * 
     * @type {Array<OgmaUser>}
     * @memberof OgmaUserAllOf
     */
    following?: Array<OgmaUser>;
    /**
     * 
     * @type {Array<CommentsThread>}
     * @memberof OgmaUserAllOf
     */
    subscribedThreads?: Array<CommentsThread>;
    /**
     * 
     * @type {Array<Report>}
     * @memberof OgmaUserAllOf
     */
    reports?: Array<Report>;
    /**
     * 
     * @type {Array<Infraction>}
     * @memberof OgmaUserAllOf
     */
    infractions?: Array<Infraction>;
    /**
     * 
     * @type {Array<Club>}
     * @memberof OgmaUserAllOf
     */
    clubsBannedFrom?: Array<Club>;
    /**
     * 
     * @type {Array<Notification>}
     * @memberof OgmaUserAllOf
     */
    notifications?: Array<Notification>;
}

export function OgmaUserAllOfFromJSON(json: any): OgmaUserAllOf {
    return OgmaUserAllOfFromJSONTyped(json, false);
}

export function OgmaUserAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): OgmaUserAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'links': !exists(json, 'links') ? undefined : json['links'],
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
        'avatarId': !exists(json, 'avatarId') ? undefined : json['avatarId'],
        'registrationDate': !exists(json, 'registrationDate') ? undefined : (new Date(json['registrationDate'])),
        'lastActive': !exists(json, 'lastActive') ? undefined : (new Date(json['lastActive'])),
        'deletedAt': !exists(json, 'deletedAt') ? undefined : (json['deletedAt'] === null ? null : new Date(json['deletedAt'])),
        'commentsThread': !exists(json, 'commentsThread') ? undefined : CommentsThreadFromJSON(json['commentsThread']),
        'userRoles': !exists(json, 'userRoles') ? undefined : (json['userRoles'] === null ? null : (json['userRoles'] as Array<any>).map(UserRoleFromJSON)),
        'stories': !exists(json, 'stories') ? undefined : ((json['stories'] as Array<any>).map(StoryFromJSON)),
        'blogposts': !exists(json, 'blogposts') ? undefined : ((json['blogposts'] as Array<any>).map(BlogpostFromJSON)),
        'roles': !exists(json, 'roles') ? undefined : ((json['roles'] as Array<any>).map(OgmaRoleFromJSON)),
        'blacklistedRatings': !exists(json, 'blacklistedRatings') ? undefined : ((json['blacklistedRatings'] as Array<any>).map(BlacklistedRatingFromJSON)),
        'blacklistedTags': !exists(json, 'blacklistedTags') ? undefined : ((json['blacklistedTags'] as Array<any>).map(BlacklistedTagFromJSON)),
        'blockers': !exists(json, 'blockers') ? undefined : ((json['blockers'] as Array<any>).map(OgmaUserFromJSON)),
        'blocking': !exists(json, 'blocking') ? undefined : ((json['blocking'] as Array<any>).map(OgmaUserFromJSON)),
        'followers': !exists(json, 'followers') ? undefined : ((json['followers'] as Array<any>).map(OgmaUserFromJSON)),
        'following': !exists(json, 'following') ? undefined : ((json['following'] as Array<any>).map(OgmaUserFromJSON)),
        'subscribedThreads': !exists(json, 'subscribedThreads') ? undefined : ((json['subscribedThreads'] as Array<any>).map(CommentsThreadFromJSON)),
        'reports': !exists(json, 'reports') ? undefined : ((json['reports'] as Array<any>).map(ReportFromJSON)),
        'infractions': !exists(json, 'infractions') ? undefined : ((json['infractions'] as Array<any>).map(InfractionFromJSON)),
        'clubsBannedFrom': !exists(json, 'clubsBannedFrom') ? undefined : ((json['clubsBannedFrom'] as Array<any>).map(ClubFromJSON)),
        'notifications': !exists(json, 'notifications') ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
    };
}

export function OgmaUserAllOfToJSON(value?: OgmaUserAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'bio': value.bio,
        'links': value.links,
        'avatar': value.avatar,
        'avatarId': value.avatarId,
        'registrationDate': value.registrationDate === undefined ? undefined : (value.registrationDate.toISOString()),
        'lastActive': value.lastActive === undefined ? undefined : (value.lastActive.toISOString()),
        'deletedAt': value.deletedAt === undefined ? undefined : (value.deletedAt === null ? null : value.deletedAt.toISOString()),
        'commentsThread': CommentsThreadToJSON(value.commentsThread),
        'userRoles': value.userRoles === undefined ? undefined : (value.userRoles === null ? null : (value.userRoles as Array<any>).map(UserRoleToJSON)),
        'stories': value.stories === undefined ? undefined : ((value.stories as Array<any>).map(StoryToJSON)),
        'blogposts': value.blogposts === undefined ? undefined : ((value.blogposts as Array<any>).map(BlogpostToJSON)),
        'roles': value.roles === undefined ? undefined : ((value.roles as Array<any>).map(OgmaRoleToJSON)),
        'blacklistedRatings': value.blacklistedRatings === undefined ? undefined : ((value.blacklistedRatings as Array<any>).map(BlacklistedRatingToJSON)),
        'blacklistedTags': value.blacklistedTags === undefined ? undefined : ((value.blacklistedTags as Array<any>).map(BlacklistedTagToJSON)),
        'blockers': value.blockers === undefined ? undefined : ((value.blockers as Array<any>).map(OgmaUserToJSON)),
        'blocking': value.blocking === undefined ? undefined : ((value.blocking as Array<any>).map(OgmaUserToJSON)),
        'followers': value.followers === undefined ? undefined : ((value.followers as Array<any>).map(OgmaUserToJSON)),
        'following': value.following === undefined ? undefined : ((value.following as Array<any>).map(OgmaUserToJSON)),
        'subscribedThreads': value.subscribedThreads === undefined ? undefined : ((value.subscribedThreads as Array<any>).map(CommentsThreadToJSON)),
        'reports': value.reports === undefined ? undefined : ((value.reports as Array<any>).map(ReportToJSON)),
        'infractions': value.infractions === undefined ? undefined : ((value.infractions as Array<any>).map(InfractionToJSON)),
        'clubsBannedFrom': value.clubsBannedFrom === undefined ? undefined : ((value.clubsBannedFrom as Array<any>).map(ClubToJSON)),
        'notifications': value.notifications === undefined ? undefined : ((value.notifications as Array<any>).map(NotificationToJSON)),
    };
}

