/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseModel,
    BaseModelFromJSON,
    BaseModelFromJSONTyped,
    BaseModelToJSON,
} from './BaseModel';
import {
    RatingAllOf,
    RatingAllOfFromJSON,
    RatingAllOfFromJSONTyped,
    RatingAllOfToJSON,
} from './RatingAllOf';

/**
 * 
 * @export
 * @interface Rating
 */
export interface Rating {
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    iconId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Rating
     */
    blacklistedByDefault?: boolean;
}

export function RatingFromJSON(json: any): Rating {
    return RatingFromJSONTyped(json, false);
}

export function RatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rating {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'iconId': !exists(json, 'iconId') ? undefined : json['iconId'],
        'blacklistedByDefault': !exists(json, 'blacklistedByDefault') ? undefined : json['blacklistedByDefault'],
    };
}

export function RatingToJSON(value?: Rating | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'order': value.order,
        'icon': value.icon,
        'iconId': value.iconId,
        'blacklistedByDefault': value.blacklistedByDefault,
    };
}

