/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseModel,
    BaseModelFromJSON,
    BaseModelFromJSONTyped,
    BaseModelToJSON,
} from './BaseModel';
import {
    ETagNamespace,
    ETagNamespaceFromJSON,
    ETagNamespaceFromJSONTyped,
    ETagNamespaceToJSON,
} from './ETagNamespace';
import {
    Story,
    StoryFromJSON,
    StoryFromJSONTyped,
    StoryToJSON,
} from './Story';
import {
    TagAllOf,
    TagAllOfFromJSON,
    TagAllOfFromJSONTyped,
    TagAllOfToJSON,
} from './TagAllOf';

/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    description?: string | null;
    /**
     * 
     * @type {ETagNamespace}
     * @memberof Tag
     */
    namespace?: ETagNamespace | null;
    /**
     * 
     * @type {Array<Story>}
     * @memberof Tag
     */
    stories?: Array<Story>;
}

export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'namespace': !exists(json, 'namespace') ? undefined : ETagNamespaceFromJSON(json['namespace']),
        'stories': !exists(json, 'stories') ? undefined : ((json['stories'] as Array<any>).map(StoryFromJSON)),
    };
}

export function TagToJSON(value?: Tag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'slug': value.slug,
        'description': value.description,
        'namespace': ETagNamespaceToJSON(value.namespace),
        'stories': value.stories === undefined ? undefined : ((value.stories as Array<any>).map(StoryToJSON)),
    };
}

