/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ETagNamespace,
    ETagNamespaceFromJSON,
    ETagNamespaceFromJSONTyped,
    ETagNamespaceToJSON,
} from './ETagNamespace';

/**
 * 
 * @export
 * @interface TagDto
 */
export interface TagDto {
    /**
     * 
     * @type {number}
     * @memberof TagDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TagDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TagDto
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TagDto
     */
    description?: string | null;
    /**
     * 
     * @type {ETagNamespace}
     * @memberof TagDto
     */
    namespace?: ETagNamespace | null;
    /**
     * 
     * @type {string}
     * @memberof TagDto
     */
    namespaceColor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TagDto
     */
    namespaceId?: number | null;
}

export function TagDtoFromJSON(json: any): TagDto {
    return TagDtoFromJSONTyped(json, false);
}

export function TagDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'namespace': !exists(json, 'namespace') ? undefined : ETagNamespaceFromJSON(json['namespace']),
        'namespaceColor': !exists(json, 'namespaceColor') ? undefined : json['namespaceColor'],
        'namespaceId': !exists(json, 'namespaceId') ? undefined : json['namespaceId'],
    };
}

export function TagDtoToJSON(value?: TagDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'slug': value.slug,
        'description': value.description,
        'namespace': ETagNamespaceToJSON(value.namespace),
        'namespaceColor': value.namespaceColor,
        'namespaceId': value.namespaceId,
    };
}

