name: Mirror
on: [push]
jobs:
  mirror:    
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://codeberg.org/Genfic/Ogma.git'
            GIT_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
            GIT_PASSWORD: ${{ secrets.CODEBERG_PASSWORD }}
